import type { ExecutionMode } from '@fleetscope/domain';

export interface FixtureCaseDescriptor {
  readonly caseId: string;
  readonly title: string;
  readonly vendor: string;
  readonly owner: string;
  readonly agentVersionRef: string;
  readonly memoryScope: string;
  readonly createdAt: string;
  readonly sessions: readonly string[];
  readonly executionMode: ExecutionMode;
  readonly provenance: {
    readonly note: string;
    readonly syntheticSystems: readonly string[];
    readonly containsPii: boolean;
    readonly containsSecrets: boolean;
  };
}

export interface EvidenceMarker {
  readonly id: string;
  readonly label: string;
  readonly service: string;
  readonly caseSequence: number;
  readonly eventId: string;
  readonly sessionId: string | null;
  readonly eventType: string;
  /** Convenience for `fleetscope_seek`. caseSequence remains authoritative. */
  readonly fraction: number;
  readonly note?: string;
}

export interface EvidenceManifest {
  readonly manifestVersion: string;
  readonly caseId: string;
  readonly eventCount: number;
  readonly firstCaseSequence: number;
  readonly lastCaseSequence: number;
  readonly schemaVersions: readonly string[];
  readonly sessions: ReadonlyArray<{
    readonly sessionId: string;
    readonly eventCount: number;
    readonly firstCaseSequence: number;
    readonly lastCaseSequence: number;
    readonly startedAt: string;
    readonly endedAt: string;
  }>;
  readonly milestones: ReadonlyArray<{
    readonly milestone: string;
    readonly caseSequence: number;
    readonly eventId: string;
    readonly fraction: number;
    readonly at: string;
  }>;
  readonly platformEvidence: readonly EvidenceMarker[];
  readonly incidents: ReadonlyArray<{
    readonly incidentId: string;
    readonly incidentClass: string;
    readonly caseSequence: number;
    readonly fraction: number;
  }>;
  readonly interventions: ReadonlyArray<{
    readonly interventionId: string;
    readonly actionTemplate: string;
    readonly lifecycle: ReadonlyArray<{
      readonly state: string;
      readonly caseSequence: number;
      readonly eventId: string;
    }>;
  }>;
  readonly approvals: ReadonlyArray<{
    readonly approvalId: string;
    readonly openedAtCaseSequence: number;
    readonly resolvedAtCaseSequence: number;
  }>;
  readonly blockedInputIds: readonly string[];
  readonly integrity: {
    readonly note: string;
    readonly canonicalEventsFile: string;
    readonly expectedStateFile: string;
  };
}

/** The blessed projection, regenerated by `pnpm fixtures:bless`. */
export interface ExpectedState {
  readonly caseId: string;
  readonly projectorVersion: string;
  readonly eventCount: number;
  /** Hash at the live edge. */
  readonly terminalStateHash: string;
  /** Hash at every significant prefix, so a regression names the exact event. */
  readonly prefixHashes: ReadonlyArray<{
    readonly caseSequence: number;
    readonly eventId: string;
    readonly stateHash: string;
  }>;
}
